/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reentrancyAttackSol from "./ReentrancyAttack.sol";
export type { reentrancyAttackSol };
import type * as presalePocSol from "./presalePOC.sol";
export type { presalePocSol };
