/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MarAbiertoTokenI__factory } from "./MarAbiertoTokenI__factory";
export { ReentrancyAttack__factory } from "./ReentrancyAttack__factory";
