/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MarAbiertoTokenI,
  MarAbiertoTokenIInterface,
} from "../../../../report/POC/ReentrancyAttack.sol/MarAbiertoTokenI";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mintPresale",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class MarAbiertoTokenI__factory {
  static readonly abi = _abi;
  static createInterface(): MarAbiertoTokenIInterface {
    return new utils.Interface(_abi) as MarAbiertoTokenIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MarAbiertoTokenI {
    return new Contract(address, _abi, signerOrProvider) as MarAbiertoTokenI;
  }
}
