/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721 } from "./IERC721";
export type { NFTReceiver } from "./NFTReceiver";
export type { NoNFTReceiver } from "./NoNFTReceiver";
